// Generated by dia2code
#ifndef RENDER__INTERACTIVEELEMENT__H
#define RENDER__INTERACTIVEELEMENT__H

#include "SFML/Graphics.hpp"

namespace render {
  class IHMState;
}

#include "IHMState.h"

namespace render {

  /// class InteractiveElement - 
  class InteractiveElement {
    // Attributes
  protected:
    sf::RectangleShape surface;
    // Operations
  public:
    InteractiveElement (int posX, int posY);
    bool checkClick (sf::Vector2f mousePos);
    void checkHover (sf::Vector2f mousePos);
    virtual void onClickEvent ();
    virtual void onHoverAction ();
    sf::RectangleShape getSurface ();
    virtual ~InteractiveElement ();
    // Setters and Getters
    void setSurface(const sf::RectangleShape& surface);
  };

};

#endif
