// Generated by dia2code
#ifndef SERVER__CLIENT__H
#define SERVER__CLIENT__H

#include <string>

#include "state/PlayerId.h"

namespace server {

  /// class Client - 
  class Client {
    // Attributes
  private:
    std::string clientName;
    state::PlayerId playerId;
    // Operations
  public:
    Client (std::string name);
    // Setters and Getters
  };

};

#endif
