// Generated by dia2code
#ifndef SERVER__CLIENT__H
#define SERVER__CLIENT__H

#include <string>
#include <chrono>

#include "state/PlayerId.h"

namespace server {

  /// class Client - 
  class Client {
    // Attributes
  private:
    std::string clientName;
    state::PlayerId playerId;
    std::chrono::time_point<std::chrono::high_resolution_clock> lastUpdate;
    // Operations
  public:
    Client (std::string name, state::PlayerId playerId);
    ~Client ();
    void updateTimestamp (const std::chrono::time_point<std::chrono::high_resolution_clock>& lastUpdate);
    const std::string& getClientName () const;
    const std::chrono::time_point<std::chrono::high_resolution_clock> & getLastUpdate () const;
    // Setters and Getters
  };

};

#endif
