// Generated by dia2code
#ifndef SERVER__COMMANDQUEUE__H
#define SERVER__COMMANDQUEUE__H

#include <string>
#include <deque>
#include <chrono>
#include <vector>

namespace server {

  /// class CommandQueue - 
  class CommandQueue {
    // Attributes
  private:
    std::deque<std::pair<std::string, std::chrono::time_point<std::chrono::high_resolution_clock>>>  commandList;
    // Operations
  public:
    std::vector<std::string> retrieveCommands (std::chrono::time_point<std::chrono::high_resolution_clock> lastUpdate);
    CommandQueue ();
    ~CommandQueue ();
    void addCommand (const std::string& commandArgs);
    // Setters and Getters
  };

};

#endif
