// Generated by dia2code
#ifndef SERVER__REQUESTHANDLER__H
#define SERVER__REQUESTHANDLER__H

#include <boost/beast.hpp>
#include <boost/beast/http.hpp>
#include <boost/asio.hpp>
#include <boost/asio/ip/tcp.hpp>

namespace server {
  class LiveGame;
}

#include "LiveGame.h"

namespace server {

  /// class requestHandler - 
  class requestHandler {
    // Operations
  public:
    static void process_request (boost::beast::http::request <boost::beast::http::string_body> & request, boost::beast::http::response <boost::beast::http::dynamic_body> & response);
  private:
    static void handlePost (boost::beast::http::request <boost::beast::http::string_body> & request, boost::beast::http::response <boost::beast::http::dynamic_body> & response);
    static void handleGet (boost::beast::http::request <boost::beast::http::string_body> & request, boost::beast::http::response <boost::beast::http::dynamic_body> & response);
    // Setters and Getters
  };

};

#endif
